[colors.bright]
black = "#666666"
blue = "#8AADF4"
cyan = "#90C6C4"
green = "#A6DA95"
magenta = "#C6A0F6"
red = "#ED8796"
white = "#E5E5E5"
yellow = "#EED49F"

[colors.normal]
black = "#666666"
blue = "#6588D9"
cyan = "#519FB0"
green = "#8FBB76"
magenta = "#8A5F9E"
red = "#E84D61"
white = "#E5E5E5"
yellow = "#FCC76A"

[colors.primary]
background = "#1F1F1F"
foreground = "#E5E5E5"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NF"
style = "SemiBold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "SemiBold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Light Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Light"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "None"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[shell]
args = ["-l"]
program = "/bin/zsh"

[window]
decorations = "none"
title = "Terminal"

[window.padding]
x = 10
y = 10
